### ISSUE TITLE
Manifest File version field broken (PACMAN-663)

### ISSUE THREAD

**Issue by higaski** [espressif/idf-component-manager#38]
### The Component Manager version

v1.3.1

### ESP-IDF Version

ESP-IDF v5.2-dev-1349-gcf7e743a9b

### python Version

Python 3.11.3

### Operating System

Arch

### Description

It is no longer possible to use the version field when referencing git branches or tags.

### To Reproduce

Add the following dependency to any project:
```yaml
  dcc:
    version: v0.27.1 # branches don't work either
    git: https://github.com/ZIMO-Elektronik/DCC.git
```

### Expected behaviour

The component manager should check out the specified tag. Valid tags **may** contain prefixes (e.g. v1.0.0).

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.
