### ISSUE TITLE
Allow modification of managed component directories, skip hash sum checking (PACMAN-687)

### ISSUE THREAD

**Issue by higaski** [espressif/idf-component-manager#40]
### Related area

missing feature regarding codegen

### Is your feature request related to a problem?

The component manager needs a feature to allow components to be modified without complaining about every minuscule thing. The prime example of why such a feature is important is code generation. Not only would I consider "in source" (so next to other actual source files) codegen to be quite common, but in some languages its even mandatory (Dart).

### Describe the solution you'd like

```yaml
my_component:
  version: master
  modifiable: true
  git: https://github.com/higaski/my_component
```

### I have checked existing list of Feature requests and I have provided enough information.

- [X] I confirm I have checked existing list of Feature requests and I have provided enough information.
