### ISSUE TITLE
Component manager can't use GIT version with leading 'v' (PACMAN-796)

### ISSUE THREAD

**Issue by higaski** [espressif/idf-component-manager#51]
### The Component Manager version

v1.4.2

### ESP-IDF Version

v5.2-beta1

### python Version

3.11.6

### Operating System

Linux

### Description

The `--version git` option does not work for GIT tags containing a leading `v` or so it seems.

I have a component with the following manifest file.

```yml
description: MDU protocol for ZPP and ZSU updates
url: http://zimo.at
documentation: https://github.com/ZIMO-Elektronik/MDU/blob/master/README.md
repository: https://github.com/ZIMO-Elektronik/MDU.git
issues: https://github.com/ZIMO-Elektronik/MDU/issues

dependencies:
  idf: ">=5.0.0"
```

The latest tag is v0.15.0

Uploading this component with 
```sh
compote component upload --namespace zimo-elektronik  --name MDU --version git --dry-run
```
does not work.

Using any tag without leading `v` does not give me any errors.
```sh
compote component upload --namespace zimo-elektronik  --name MDU --version 1.2.3 --dry-run
```

For some weird reason 

### To Reproduce

```cpp
.
```

### Expected behaviour

GIT version should be parsed correctly according to https://semver.org/

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.
